# The hpcc-default service account is used by ay component that doesn't need API access to launch child jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpcc-default
---
# The hpcc-agent service account is used by any component that DOES need API access to launch child jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpcc-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpcc-agent
rules:
  - apiGroups: [ "" ] # core API group
    resources: [ "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "create", "list", "delete", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpcc-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpcc-agent
subjects:
  - kind: ServiceAccount
    name: hpcc-agent
    namespace: {{ .Release.Namespace }}
