apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastorage-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.dataStorage.storageSize }}
