apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dllserver-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.dllserver.storageSize }}
