name: Check win32 compiles

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display build summary
        env:
          OPTION: x64
        working-directory: .
        run: |
          $vcpkg_root = $(get-command vcpkg | Select-Object -ExpandProperty Source | Split-Path)
          echo Option:$Env:OPTION
          echo "Checkout to $Env:GITHUB_WORKSPACE"
          echo "vcpkg @$(get-command vcpkg | Select-Object -ExpandProperty Source | Split-Path)"
          echo "vcpkg @$vcpkg_root"
      - name: Install bison
        working-directory: .
        run: |
          choco install winflexbison3 -y
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup msvc environment
        uses: hpcc-systems/msvc-dev-cmd@v1
      - name: Windows compilation
        working-directory: .
        run: |
          mkdir build
          cd build
          $vcpkg_root = $(get-command vcpkg | Select-Object -ExpandProperty Source | Split-Path)
          echo "cmake $Env:GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE=$vcpkg_root\scripts\buildsystems\vcpkg.cmake -DUSE_OPENLDAP=0 -DUSE_ICU=0 -DUSE_LIBXSLT=0 -DUSE_CBLAS=0 -DUSE_ZLIB=0 -DUSE_LIBARCHIVE=0 -DUSE_BOOST_REGEX=0 -DUSE_OPENSSL=0 -DUSE_APR=0 -DUSE_AZURE=0 -DUSE_AWS=0 -DSUPPRESS_JAVAEMBED=1 -DWSSQL_SERVICE=0 -DUSE_PYTHON3=0 -DUSE_PYTHON2=0 -DUSE_CASSANDRA=0 -DCMAKE_GENERATOR_PLATFORM=x64"
          cmake $Env:GITHUB_WORKSPACE  -G "NMake Makefiles" -DUSE_OPENLDAP=0 -DUSE_ICU=0 -DUSE_LIBXSLT=0 -DUSE_CBLAS=0 -DUSE_ZLIB=0 -DUSE_LIBARCHIVE=0 -DUSE_BOOST_REGEX=0 -DUSE_OPENSSL=0 -DUSE_APR=0 -DUSE_AZURE=0 -DUSE_AWS=0 -DSUPPRESS_JAVAEMBED=1 -DWSSQL_SERVICE=0 -DUSE_PYTHON3=0 -DUSE_PYTHON2=0 -DUSE_CASSANDRA=0 -DUSE_TBB=0 -DUSE_JAVA=0 -DUSE_NATIVE_LIBRARIES=1 -DINCLUDE_CONFIG_MANAGER=0 -DINCLUDE_TREEVIEW=0
          nmake /i
#          cmake $Env:GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE=$vcpkg_root\scripts\buildsystems\vcpkg.cmake -DUSE_OPENLDAP=0 -DUSE_ICU=0 -DUSE_LIBXSLT=0 -DUSE_CBLAS=0 -DUSE_ZLIB=0 -DUSE_LIBARCHIVE=0 -DUSE_BOOST_REGEX=0 -DUSE_OPENSSL=0 -DUSE_APR=0 -DUSE_AZURE=0 -DUSE_AWS=0 -DSUPPRESS_JAVAEMBED=1 -DWSSQL_SERVICE=0 -DUSE_PYTHON3=0 -DUSE_PYTHON2=0 -DUSE_CASSANDRA=0 -DCMAKE_GENERATOR_PLATFORM=x64
#          cmake .. -DUSE_TBB=0
#          nmake
#      - name: Install node
#        working-directory: .
#        run: |
#          choco install nodejs -y
#      - name: Install vcpkg dependencies
#        working-directory: . 
#        run: |
#          echo install packages
#          vcpkg install zlib
